# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "quent-v2-query-engine-model"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
quent-attributes = { path = "../../../../crates/attributes" }
quent-v2-instrumentation = { path = "../../../../crates/v2/instrumentation" }
quent-v2-model = { path = "../../../../crates/v2/model" }
quent-v2-model-ir = { path = "../../../../crates/v2/model-ir" }
uuid = { workspace = true }
