[package]
name = "quent-bench-cpp-bridge"
version.workspace = true
edition.workspace = true
publish.workspace = true
build = "build.rs"

[lib]
crate-type = ["cdylib", "staticlib"]
test = false

[dependencies]
cxx = "1"
quent-dynamic-attributes.workspace = true
quent-instrumentation.workspace = true
quent-io.workspace = true
serde.workspace = true

[build-dependencies]
quent-bench-build-support.workspace = true
