// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! FSM syntax and lowering to the FSM schema constraint.

use indexmap::IndexMap;
use quent_fsm::{FsmEntityBuilder, FsmEntityBuilderError, StateDecl};
use quent_schema::{Entity, Record};
use serde::Deserialize;

use crate::ast::{AnnotationMap, Field};
use crate::constraints::resource::{self, Lowerer as ResourceLowerer, ResourceDecl};
use crate::diag::Diagnostics;
use crate::lower::{annotations_builder, build_or_diagnose, event_fields, ident, type_decl_ident};

/// An FSM entity: annotations plus its states.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct FsmSpec {
    #[serde(default)]
    pub(crate) doc: Option<String>,
    #[serde(default)]
    pub(crate) constraints: AnnotationMap,
    #[serde(default)]
    pub(crate) metadata: AnnotationMap,

    // Constraint-related AST nodes.
    pub(crate) states: IndexMap<String, StateSpec>,
    #[serde(default)]
    pub(crate) resource: Option<ResourceDecl>,
}

/// One state of an FSM.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct StateSpec {
    #[serde(default)]
    pub(crate) attributes: IndexMap<String, Field>,

    // Constraint-related AST nodes.
    #[serde(default)]
    pub(crate) initial: bool,
    /// States the FSM can transition to. An empty list makes this a final state.
    #[serde(default)]
    pub(crate) to: Vec<String>,
}

/// Lower an FSM entity and any records generated by its resource declaration.
///
/// Its states become entity events with cardinality derived from the topology.
/// Invalid FSMs are reported and skipped.
pub(crate) fn lower(
    name: &str,
    spec: &FsmSpec,
    resources: &ResourceLowerer,
    sink: &mut Diagnostics,
) -> Option<(Entity, Vec<Record>)> {
    let path = format!("fsms.{name}");
    let id = type_decl_ident(name, "fsms", sink);
    let mut anns = annotations_builder(&spec.doc, &spec.constraints, &spec.metadata, &path, sink);

    let (records, bounds_record, resource_constraint) = match (id.clone(), &spec.resource) {
        (Some(id), Some(resource)) => resources.lower(name, id, resource, &path, sink),
        _ => (Vec::new(), None, None),
    };
    if let Some(data) = resource_constraint {
        anns = resource::attach_constraint(anns, data);
    }

    // Lower the states before rejecting the entity name so diagnostics inside
    // independent states are still reported.
    let mut states = Vec::new();
    let mut complete = true;
    for (state_name, state) in &spec.states {
        let Some(state_id) = ident(state_name, &path, sink) else {
            complete = false;
            continue;
        };
        let attributes = event_fields(
            &state.attributes,
            &format!("{path}.states.{state_name}"),
            bounds_record.as_ref(),
            resources,
            sink,
        );
        let to = state
            .to
            .iter()
            .filter_map(|target| ident(target, &path, sink))
            .collect();
        states.push(StateDecl {
            name: state_id,
            attributes,
            to,
            initial: state.initial,
        });
    }

    // Structural checks on a reduced state set would produce misleading
    // diagnostics, such as reporting that the initial state is missing.
    let id = id?;
    if !complete {
        return None;
    }

    let built = FsmEntityBuilder::new(id)
        .with_annotations(build_or_diagnose(anns.build(), &path, sink).unwrap_or_default())
        .with_states(states)
        .build();
    match built {
        Ok(entity) => Some((entity, records)),
        Err(error) => {
            shape_error(&error, &path, sink);
            None
        }
    }
}

/// Report an FSM structural error in the YAML's own terms.
fn shape_error(error: &FsmEntityBuilderError, path: &str, sink: &mut Diagnostics) {
    match error {
        FsmEntityBuilderError::NoInitialState => {
            sink.error(path, "no state marked `initial: true`", None);
        }
        FsmEntityBuilderError::MultipleInitialStates(_) => {
            sink.error(path, "more than one state marked `initial: true`", None);
        }
        FsmEntityBuilderError::Invalid(error) => {
            sink.error(path, error.to_string(), None);
        }
        other => sink.error(path, other.to_string(), None),
    }
}
