[package]
name = "quent-collector-python"
edition.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
http.workspace = true
pyo3.workspace = true
quent-collector = { path = "../server" }
quent-collector-proto = { path = "../proto" }
tokio = { workspace = true, features = ["rt-multi-thread", "sync"] }
tokio-stream = { workspace = true, features = ["net"] }
tonic.workspace = true
uuid.workspace = true
