[package]
name = "quent-query-engine-model"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
quent-dynamic-attributes = { path = "../../../crates/dynamic-attributes", features = ["serde"] }
quent-events = { path = "../../../crates/events", features = ["serde"] }
serde.workspace = true
uuid = { workspace = true, features = ["serde", "v7"] }
