[package]
name = "quent-simulator-instrumentation"
version.workspace = true
edition.workspace = true
publish.workspace = true

[features]
collector = ["quent-instrumentation/io-collector"]

[dependencies]
quent-events = { path = "../../../crates/events" }
quent-instrumentation = { path = "../../../crates/instrumentation", features = [
    "io-msgpack",
    "io-ndjson",
    "io-postcard",
] }
quent-store = { path = "../../../crates/store" }
serde = { workspace = true, features = ["derive"] }

[build-dependencies]
quent-instrumentation-build = { path = "../../../crates/instrumentation-build" }
quent-store-build = { path = "../../../crates/store-build" }
quent-yaml = { path = "../../../crates/yaml" }

[dev-dependencies]
quent-collector-client = { path = "../../../crates/collector/client" }
