// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityListEntry } from "./EntityListEntry";
import type { TimelineRequest } from "./TimelineRequest";

/**
 * A single UI refresh: any combination of timeline and entity-list queries,
 * sharing one set of application parameters.
 */
export type BulkRequest<GlobalParams, TimelineParams> = { 
/**
 * Application parameters shared by every query in the bundle.
 */
app_params: GlobalParams, 
/**
 * Timeline queries, keyed by a caller-chosen id.
 */
timelines: { [key in string]?: TimelineRequest<TimelineParams> } | null, 
/**
 * Entity-list queries, keyed by a caller-chosen id.
 */
entities: { [key in string]?: EntityListEntry } | null, };
