// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BulkEntityListResponseEntry } from "./BulkEntityListResponseEntry";

/**
 * Response for a bulk entity-list request, keyed by the request entry ids.
 */
export type BulkEntityListResponse = { entries: { [key in string]?: BulkEntityListResponseEntry }, };
