// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BulkEntityListResponse } from "./BulkEntityListResponse";
import type { BulkTimelinesResponse } from "./BulkTimelinesResponse";

/**
 * Response to a [`BulkRequest`]; each section is present iff requested.
 */
export type BulkResponse = { timelines: BulkTimelinesResponse | null, entities: BulkEntityListResponse | null, };
