// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityListResponse } from "./EntityListResponse";

/**
 * A single entry in a bulk entity-list response.
 */
export type BulkEntityListResponseEntry = { "status": "ok" } & EntityListResponse | { "status": "error", 
/**
 * A message describing the error.
 */
message: string, };
