// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityListFilter } from "./EntityListFilter";
import type { PageParams } from "./PageParams";
import type { Sort } from "./Sort";
import type { TimeWindow } from "./TimeWindow";

/**
 * A single entity-list query, without application parameters.
 */
export type EntityListEntry = { window: TimeWindow, filter: EntityListFilter, sort: Sort, 
/**
 * `None` returns the full filtered set.
 */
page: PageParams | null, };
