// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityScope } from "./EntityScope";

/**
 * Entity filters. Every set field must match; a `None` field does not filter.
 */
export type EntityListFilter = { 
/**
 * Restrict to entities with a usage on this scope. `None` lists entities
 * regardless of which resource they used.
 */
scope: EntityScope | null, entity_type_name: string | null, 
/**
 * Keep only entities with resource usages longer than this threshold. Note
 * that only Fsm-type entities can have usages.
 */
min_usage_s: number | null, };
