// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityListItem } from "./EntityListItem";

/**
 * A ranked, paged list of entities.
 */
export type EntityListResponse = { items: Array<EntityListItem>, 
/**
 * The count of entities matching the filter before paging.
 */
total: number, };
