// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FiniteStateMachine } from "./FiniteStateMachine";

/**
 * An entity and its longest matching resource usage.
 */
export type EntityListItem = { entity: FiniteStateMachine, usage_duration_s: number, };
