// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityListEntry } from "./EntityListEntry";

/**
 * Parameters for listing entities.
 */
export type EntityListRequest<AppParams> = { entry: EntityListEntry, 
/**
 * Application-specific request parameters, e.g. for filtering.
 */
app_params: AppParams, };
