// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reference to an entity related to an FSM transition.
 */
export type FsmEntityRef = { id: string, type_name: string, instance_name: string, };
