// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PageParams } from "./PageParams";

/**
 * Parameters for requesting long entities in a resource timeline
 */
export type LongEntitiesParams = { 
/**
 * Fully include entities that have usages exceeding this amount of time.
 */
threshold_s: number, 
/**
 * Parameters of the page of long entities. If this is not set, return
 * all long entities.
 */
page: PageParams | null, };
