// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LongEntitiesPageParams = { 
/**
 * Maximum number of long entities per page.
 */
max: number, 
/**
 * Zero-based page index into long entities.
 */
long_entities_page: number, };
