// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FiniteStateMachine } from "./FiniteStateMachine";

/**
 * Long entities in resource timelines.
 */
export type LongEntities = { 
/**
 * FSMs that have usage spans exceeding the long entities threshold.
 *
 * This may be empty if no long entities exist or if they were not requested.
 * If pagination is requested, this will only hold one page.
 */
long_fsms: Array<FiniteStateMachine>, 
/**
 * Total number of long FSMs, before pagination.
 */
long_fsms_total: number, };
