// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-entry timeline-request parameter; restricts a resource timeline to the
 * given operators, or all operators when empty.
 */
export type OperatorFilter = { operator_ids: Array<string>, };
