// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters of paginated APIs.
 */
export type PageParams = { 
/**
 * Maximum number of items per page.
 */
max: number, 
/**
 * The zero-based page index requested.
 */
page: number, };
