// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A zero-based page of at most `max` items.
 */
export type PageParams = { max: number, page: number, };
