// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityFilter } from "./EntityFilter";
import type { TimelineConfig } from "./TimelineConfig";

/**
 * Parameters for requesting a resource group timeline.
 */
export type ResourceGroupTimelineRequest<TimelineParams> = { 
/**
 * The ID of the resource group
 */
resource_group_id: string, 
/**
 * The type name of the leaf resources for which to produce the timeline
 * for this group.
 */
resource_type_name: string, 
/**
 * If set, fully include entities that have usages exceeding this amount of
 * time in seconds.
 */
long_entities_threshold_s: number | null, 
/**
 * Maximum number of long entities to return (page size). `None` or `0`
 * returns all of them. Applied after threshold filtering and ranking.
 */
long_entities_max?: number, 
/**
 * Zero-based page index into the ranked long entities. `None` is page 0.
 */
long_entities_page?: number, 
/**
 * Entity filters.
 */
entity_filter: EntityFilter, 
/**
 * Application-specific request parameters, e.g. for filtering.
 */
app_params: TimelineParams, 
/**
 * The configuration of the window and number of bins.
 */
config: TimelineConfig, };
