// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityFilter } from "./EntityFilter";
import type { LongEntitiesParams } from "./LongEntitiesParams";
import type { TimelineConfig } from "./TimelineConfig";

/**
 * Parameters for requesting a resource timeline.
 */
export type ResourceTimelineRequest<TimelineParams> = { 
/**
 * The ID of the resource
 */
resource_id: string, 
/**
 * Parameters for dealing with long entities.
 *
 * If this is not set, then no long entities are returned.
 */
long_entities: LongEntitiesParams | null, 
/**
 * Entity filters.
 */
entity_filter: EntityFilter, 
/**
 * Application-specific request parameters, e.g. for filtering.
 */
application: TimelineParams, 
/**
 * The configuration of the window and number of bins.
 */
config: TimelineConfig, };
