// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BinnedSpanSec } from "./BinnedSpanSec";
import type { FiniteStateMachine } from "./FiniteStateMachine";

export type ResourceTimelineBinned = { 
/**
 * The configuration of the binned timeline.
 */
config: BinnedSpanSec, 
/**
 * Maps a resource capacity name to a vector where each element holds an
 * aggregated value of a time bin.
 */
capacities_values: { [key in string]?: Array<number> }, 
/**
 * Ranked page of FSMs whose usage spans exceed the long_entities_threshold,
 * longest first. Sliced per the request's `long_entities_max`/`_page`.
 */
long_fsms: Array<FiniteStateMachine>, 
/**
 * Total number of long FSMs matching the threshold before pagination, so
 * clients can compute the page count.
 */
long_fsms_total: number, };
