// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntitySortKey } from "./EntitySortKey";
import type { SortDir } from "./SortDir";

export type Sort = { key: EntitySortKey, dir: SortDir, };
