// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A time window in seconds relative to the query epoch.
 */
export type TimeWindow = { start: number, end: number, };
