[package]
name = "quent-v2-model-ir"
version.workspace = true
edition.workspace = true
publish.workspace = true

[features]
default = ["serde"]
serde = ["dep:serde", "uuid/serde"]

[dependencies]
uuid = { workspace = true, features = ["v7"] }
serde = { workspace = true, optional = true }
thiserror.workspace = true
