[package]
name = "quent-io-bitcode"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
async-trait.workspace = true
bitcode.workspace = true
quent-events = { path = "../../events", features = ["bitcode", "serde"] }
quent-io-types = { path = "../types" }
rayon.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["sync", "fs", "io-util"] }
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile = "3"
tokio = { workspace = true, features = ["macros", "rt"] }
