[package]
name = "quent-v2-resource-macros"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
proc-macro = true

[features]
default = ["ir"]
ir = []

[dependencies]
syn = { version = "2", features = ["full", "extra-traits"] }
quote = "1"
proc-macro2.workspace = true
quent-v2-model-ir = { path = "../model-ir" }
