[package]
name = "quent-instrumentation"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
quent-build-info = { path = "../build-info" }
quent-events = { path = "../events" }
quent-io = { path = "../io" }
tokio = { workspace = true, features = ["rt-multi-thread", "sync"]}
tokio-util.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
ciborium = "0.2.2"
criterion = { version = "0.5", features = ["html_reports"] }
http.workspace = true
pprof = { version = "0.14", features = ["criterion", "flamegraph"] }
quent-collector = { path = "../collector/server" }
quent-collector-proto = { path = "../collector/proto" }
quent-io = { path = "../io", features = ["callback"] }
serde = { workspace = true, features = ["derive"] }
tempfile = "3"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tokio-stream.workspace = true
tonic.workspace = true

[[bench]]
name = "event_emit"
harness = false
