// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Generic analyzed FSM reconstructed from model-generated events.
//!
//! `FsmEvents<T, D>` delegates model-specific interpretation to `D`.

use std::marker::PhantomData;

use quent_dynamic_attributes::DynamicAttribute;
use quent_events::Event;
use quent_model::{FsmEvent, ModelBuilder, analyze::TransitionInfo};
use quent_time::{OrderKey, OrderedCollector, TimeUnixNanoSec, Timestamp, span::SpanUnixNanoSec};
use smallvec::SmallVec;
use uuid::Uuid;

use crate::{
    AnalyzerError, AnalyzerResult, Entity,
    fsm::{Fsm, FsmTypeDecl, FsmTypeDeclaration, FsmUsages, Transition},
    resource::{CapacityValue, Usage, Using},
};

/// Interprets model-specific FSM transition data.
pub trait FsmDescriptor<T> {
    /// Returns the state entered by `transition`.
    fn state_name(transition: &T) -> &'static str;

    /// Returns the instance name supplied by `transition`, if any.
    fn instance_name(transition: &T) -> Option<&str>;

    /// Returns the resource claims active in the entered state.
    fn usages(transition: &T) -> SmallVec<[AnalyzedUsage; 1]>;

    /// Returns dynamically typed attributes for `transition`.
    fn attributes(transition: &T) -> Vec<DynamicAttribute>;

    /// Returns the FSM entity type name.
    fn type_name() -> &'static str;

    /// Returns the run-time FSM declaration.
    fn declaration() -> FsmTypeDecl;
}

/// Descriptor for transition enums generated by the legacy model macros.
pub struct LegacyFsmDescriptor;

/// A single transition in an analyzed FSM.
pub struct TransitionEvent<T, D = LegacyFsmDescriptor> {
    /// Per-instance transition sequence number.
    pub seq: u16,
    timestamp: TimeUnixNanoSec,
    state_name: &'static str,
    pub usages: SmallVec<[AnalyzedUsage; 1]>,
    /// The original model transition data.
    pub data: T,
    descriptor: PhantomData<D>,
}

impl<T, D> std::fmt::Debug for TransitionEvent<T, D> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("TransitionEvent")
            .field("seq", &self.seq)
            .field("timestamp", &self.timestamp)
            .field("state_name", &self.state_name)
            .field("usages", &self.usages)
            .finish_non_exhaustive()
    }
}

#[derive(Debug)]
pub struct AnalyzedUsage {
    pub resource_id: Uuid,
    pub capacities: SmallVec<[CapacityValue; 3]>,
}

impl<T: TransitionInfo> FsmDescriptor<T> for LegacyFsmDescriptor {
    fn state_name(transition: &T) -> &'static str {
        transition.state_name()
    }

    fn instance_name(transition: &T) -> Option<&str> {
        transition.instance_name()
    }

    fn usages(transition: &T) -> SmallVec<[AnalyzedUsage; 1]> {
        transition
            .usages()
            .into_iter()
            .map(|usage| AnalyzedUsage {
                resource_id: usage.resource_id,
                capacities: usage
                    .capacities
                    .into_iter()
                    .map(|capacity| CapacityValue::new(capacity.name, capacity.value.unwrap_or(0)))
                    .collect(),
            })
            .collect()
    }

    fn attributes(transition: &T) -> Vec<DynamicAttribute> {
        transition.attributes()
    }

    fn type_name() -> &'static str {
        T::fsm_type_name()
    }

    fn declaration() -> FsmTypeDecl {
        use crate::fsm::{FsmStateTypeDecl, FsmTransitionDecl};

        let mut builder = ModelBuilder::new("");
        T::collect_model(&mut builder);
        let fsm_def = builder.fsms.into_iter().next().unwrap();

        let states = fsm_def
            .states
            .into_iter()
            .map(|state| FsmStateTypeDecl {
                name: state.name,
                usages: state
                    .usages
                    .iter()
                    .map(|usage| usage.field_name.clone())
                    .collect(),
            })
            .collect();

        let mut transitions = Vec::new();
        for transition in &fsm_def.transitions {
            use quent_model::TransitionEndpoint as Endpoint;
            match (&transition.from, &transition.to) {
                (Endpoint::Entry, Endpoint::State(to)) => {
                    transitions.push(FsmTransitionDecl::Entry(to.clone()));
                }
                (Endpoint::State(from), Endpoint::State(to)) => {
                    transitions.push(FsmTransitionDecl::Transition(from.clone(), to.clone()));
                }
                (Endpoint::State(from), Endpoint::Exit) => {
                    transitions.push(FsmTransitionDecl::Transition(
                        from.clone(),
                        "exit".to_owned(),
                    ));
                    transitions.push(FsmTransitionDecl::Exit("exit".to_owned()));
                }
                _ => {}
            }
        }

        FsmTypeDecl {
            name: T::fsm_type_name().to_owned(),
            states,
            transitions,
        }
    }
}

impl<T, D> Timestamp for TransitionEvent<T, D> {
    fn timestamp(&self) -> TimeUnixNanoSec {
        self.timestamp
    }
}

impl<T, D> OrderKey for TransitionEvent<T, D> {
    type Key = (TimeUnixNanoSec, u16);

    fn order_key(&self) -> Self::Key {
        (self.timestamp, self.seq)
    }
}

impl<T, D: FsmDescriptor<T>> Transition for TransitionEvent<T, D> {
    fn name(&self) -> &str {
        self.state_name
    }

    fn attributes(&self) -> Vec<DynamicAttribute> {
        D::attributes(&self.data)
    }
}

pub struct UsageWithSpan<'a> {
    entity_id: Uuid,
    usage: &'a AnalyzedUsage,
    span: SpanUnixNanoSec,
}

impl<'a> Usage<'a> for UsageWithSpan<'a> {
    fn entity_id(&self) -> Uuid {
        self.entity_id
    }
    fn resource_id(&self) -> Uuid {
        self.usage.resource_id
    }
    fn capacities(&self) -> impl Iterator<Item = &'a CapacityValue> {
        self.usage.capacities.iter()
    }
    fn span(&self) -> SpanUnixNanoSec {
        self.span
    }
}

/// Builder for reconstructing an `FsmEvents` from model events.
pub struct FsmEventsBuilder<T, D = LegacyFsmDescriptor> {
    id: Uuid,
    instance_name: String,
    transitions: OrderedCollector<TransitionEvent<T, D>>,
    descriptor: PhantomData<D>,
}

impl<T, D: FsmDescriptor<T>> FsmEventsBuilder<T, D> {
    pub fn try_new(id: Uuid) -> AnalyzerResult<Self> {
        if id.is_nil() {
            Err(AnalyzerError::Validation(
                "fsm id cannot be nil".to_string(),
            ))
        } else {
            Ok(Self {
                id,
                instance_name: String::new(),
                transitions: OrderedCollector::default(),
                descriptor: PhantomData,
            })
        }
    }

    /// Return the id of the FSM being built.
    pub fn id(&self) -> Uuid {
        self.id
    }

    /// Adds one model transition event.
    pub fn push_transition(&mut self, seq: u16, event: Event<T>) {
        let transition = event.data;
        let state_name = D::state_name(&transition);
        // Capture instance name from the first transition that provides one.
        if self.instance_name.is_empty()
            && let Some(name) = D::instance_name(&transition)
        {
            self.instance_name = name.to_owned();
        }
        self.transitions.push(TransitionEvent {
            seq,
            timestamp: event.timestamp,
            state_name,
            usages: D::usages(&transition),
            data: transition,
            descriptor: PhantomData,
        });
    }

    pub fn try_build(self) -> AnalyzerResult<FsmEvents<T, D>> {
        let transitions: SmallVec<[TransitionEvent<T, D>; 4]> =
            self.transitions.into_inner().into();
        Ok(FsmEvents {
            id: self.id,
            instance_name: self.instance_name,
            transitions,
        })
    }
}

impl<T: TransitionInfo> FsmEventsBuilder<T, LegacyFsmDescriptor> {
    /// Adds one legacy model transition event.
    pub fn push(&mut self, event: Event<FsmEvent<T>>) {
        let FsmEvent { seq, state } = event.data;
        self.push_transition(seq, Event::new(event.id, event.timestamp, state));
    }
}

/// A generic analyzed FSM reconstructed from model-generated events.
///
/// `T` is the transition enum (e.g., `TaskTransition`), which implements
/// `TransitionInfo`. Application-specific data can be accessed via
/// `transitions()` and pattern matching on `T` variants.
///
/// Implements `Entity`, `Fsm`, `FsmUsages`, `Using`, and `FsmTypeDeclaration`.
pub struct FsmEvents<T, D = LegacyFsmDescriptor> {
    id: Uuid,
    instance_name: String,
    transitions: SmallVec<[TransitionEvent<T, D>; 4]>,
}

impl<T, D> std::fmt::Debug for FsmEvents<T, D> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("FsmEvents")
            .field("id", &self.id)
            .field("instance_name", &self.instance_name)
            .field("transitions", &self.transitions)
            .finish()
    }
}

impl<T, D: FsmDescriptor<T>> FsmEvents<T, D> {
    pub fn transitions(&self) -> &[TransitionEvent<T, D>] {
        &self.transitions
    }

    /// Access the first transition's data (typically the entry state).
    pub fn first_data(&self) -> Option<&T> {
        self.transitions.first().map(|t| &t.data)
    }
}

impl<T, D: FsmDescriptor<T>> Entity for FsmEvents<T, D> {
    fn id(&self) -> Uuid {
        self.id
    }
    fn type_name(&self) -> &str {
        D::type_name()
    }
    fn instance_name(&self) -> &str {
        &self.instance_name
    }
}

impl<T, D: FsmDescriptor<T>> Fsm for FsmEvents<T, D> {
    type TransitionType = TransitionEvent<T, D>;
    fn len(&self) -> usize {
        self.transitions.len().saturating_sub(1)
    }
    fn transition(&self, index: usize) -> Option<&Self::TransitionType> {
        self.transitions.get(index)
    }
}

impl<'a, T: 'a, D: FsmDescriptor<T> + 'a> FsmUsages<'a> for FsmEvents<T, D> {
    fn usages_with_state_names(&'a self) -> impl Iterator<Item = (&'a str, impl Usage<'a>)> {
        self.transitions.windows(2).flat_map(move |window| {
            let name = window[0].state_name;
            let start = window[0].timestamp();
            let end = window[1].timestamp();
            let span = SpanUnixNanoSec::try_new(start, end).unwrap();
            window[0].usages.iter().map(move |u| {
                (
                    name,
                    UsageWithSpan {
                        entity_id: self.id,
                        usage: u,
                        span,
                    },
                )
            })
        })
    }
}

impl<T, D: FsmDescriptor<T>> Using for FsmEvents<T, D> {
    fn usages<'a>(&'a self) -> impl Iterator<Item = impl Usage<'a>> {
        self.transitions.windows(2).flat_map(move |window| {
            let start = window[0].timestamp();
            let end = window[1].timestamp();
            let span = SpanUnixNanoSec::try_new(start, end).unwrap();
            window[0].usages.iter().map(move |u| UsageWithSpan {
                entity_id: self.id,
                usage: u,
                span,
            })
        })
    }
}

impl<T, D: FsmDescriptor<T>> FsmTypeDeclaration for FsmEvents<T, D> {
    fn fsm_type_declaration() -> FsmTypeDecl {
        D::declaration()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[derive(Debug, PartialEq, Eq)]
    struct TestTransition(u8);

    impl TransitionInfo for TestTransition {
        fn state_name(&self) -> &'static str {
            "test"
        }

        fn usages(&self) -> Vec<quent_model::analyze::ExtractedUsage> {
            Vec::new()
        }

        fn instance_name(&self) -> Option<&str> {
            None
        }

        fn parent_group_id(&self) -> Option<Uuid> {
            None
        }

        fn fsm_type_name() -> &'static str {
            "test"
        }

        fn collect_model(_: &mut ModelBuilder) {}
    }

    #[test]
    fn equal_timestamp_transitions_are_ordered_by_sequence() {
        let id = Uuid::from_u128(1);
        let mut builder = FsmEventsBuilder::try_new(id).unwrap();
        builder.push(Event::new(
            id,
            100,
            FsmEvent {
                seq: 1,
                state: TestTransition(1),
            },
        ));
        builder.push(Event::new(
            id,
            100,
            FsmEvent {
                seq: 0,
                state: TestTransition(0),
            },
        ));

        let fsm = builder.try_build().unwrap();
        assert_eq!(
            fsm.transitions()
                .iter()
                .map(|transition| (transition.seq, transition.data.0))
                .collect::<Vec<_>>(),
            [(0, 0), (1, 1)]
        );
    }

    #[test]
    fn sequence_wrap_is_ordered_by_timestamp() {
        let id = Uuid::from_u128(1);
        let mut builder = FsmEventsBuilder::try_new(id).unwrap();
        builder.push(Event::new(
            id,
            101,
            FsmEvent {
                seq: 0,
                state: TestTransition(0),
            },
        ));
        builder.push(Event::new(
            id,
            100,
            FsmEvent {
                seq: u16::MAX,
                state: TestTransition(1),
            },
        ));

        let fsm = builder.try_build().unwrap();
        assert_eq!(
            fsm.transitions()
                .iter()
                .map(|transition| (transition.timestamp(), transition.seq))
                .collect::<Vec<_>>(),
            [(100, u16::MAX), (101, 0)]
        );
    }
}
