// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! Type definitions of entity events.

mod entity_ref;

use quent_time::{OrderKey, TimeUnixNanoSec, Timestamp, timestamp};
#[cfg(feature = "serde")]
use serde::{Deserialize, Serialize};

pub use entity_ref::{AnyEntity, EntityRef};
pub use quent_build_info as build_info;
pub use quent_dynamic_attributes::DynamicAttributes;
pub use uuid::Uuid;

/// Types that represent an entity's event payload.
///
/// The event payload is typically an enum where each variant represents one
/// type of event emitted by an entity according to the application event model.
///
/// The types and their implementation of this trait are automartically
/// generated by Quent's code generation.
pub trait EventPayload {
    /// The schema path to the associated entity, used to route and store the
    /// entity's events.
    const NAME: &'static str;
}

/// Associates an entity marker type with its event payload type.
///
/// An entity marker type is used in various ways:
///
/// - It identifies one entity in the application event model.
/// - It associates that entity with its event payload type.
/// - It selects its observer and handle types in the instrumentation API.
///
/// The types and their implementation of this trait are automartically
/// generated by Quent's code generation.
pub trait EntityMarker {
    /// Event payload type associated with this entity marker.
    type Payload: EventPayload;
}

/// Associates a model marker with its identity.
///
/// A model marker has various roles:
///
/// - It is the model type parameter for the instrumentation API's `Context`.
/// - It identifies the application event model with a stable name via
///   [`Self::NAME`].
/// - It provides model and source provenance via [`Self::model_info`] when it
///   implements [`build_info::ModelSource`].
///
/// The types and their implementation of this trait are automartically
/// generated by Quent's code generation.
pub trait EventModel {
    /// Stable model name recorded in artifact provenance.
    const NAME: &'static str;

    /// Returns the model identity and source provenance written with artifacts.
    fn model_info() -> build_info::ModelInfo
    where
        Self: build_info::ModelSource,
    {
        build_info::model_info::<Self>(Self::NAME)
    }
}

/// Associates a model marker with a combined event payload type.
///
/// A combined event payload type is typically an enum type combining the
/// payloads of all event types of an application event model.
///
/// The types and their implementation of this trait are automartically
/// generated by Quent's code generation.
pub trait CombinedEventModel {
    /// Model-wide event type to which entity events can be converted.
    type CombinedEvent;
}

/// The event data emitted by entities.
#[cfg_attr(feature = "serde", derive(Deserialize, Serialize))]
#[derive(Debug)]
pub struct Event<P> {
    /// The ID of the entity producing this event.
    pub id: Uuid,
    /// The timestamp of the event.
    pub timestamp: TimeUnixNanoSec,
    /// The event payload.
    pub data: P,
}

impl<P> Event<P> {
    #[inline(always)]
    pub fn new_now(id: Uuid, data: P) -> Self {
        Self {
            id,
            timestamp: timestamp(),
            data,
        }
    }

    #[inline(always)]
    pub fn new(id: Uuid, timestamp: TimeUnixNanoSec, data: P) -> Self {
        Self {
            id,
            timestamp,
            data,
        }
    }
}

impl<P> Timestamp for Event<P> {
    fn timestamp(&self) -> TimeUnixNanoSec {
        self.timestamp
    }
}

impl<P> OrderKey for Event<P> {
    type Key = TimeUnixNanoSec;

    fn order_key(&self) -> Self::Key {
        self.timestamp
    }
}
