[package]
name = "quent-v2-model"
version.workspace = true
edition.workspace = true
publish.workspace = true

[features]
default = ["serde"]
serde = ["dep:serde", "quent-v2-model-macros/serde", "uuid/serde"]

[dependencies]
uuid = { workspace = true, features = ["v7"] }
serde = { workspace = true, optional = true }
petgraph.workspace = true
quent-attributes = { path = "../../attributes" }
quent-v2-model-macros = { path = "../model-macros" }
quent-events = { path = "../../events" }
quent-exporter = { path = "../../exporter" }
quent-instrumentation = { path = "../../instrumentation" }
quent-time = { path = "../../time" }
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true
trybuild = "1"
